import { auditTableDdlScript } from "./audit-ddl.js";
import { assertValidTableName } from "./validator.js";

/**
 * Generate the DDL needed to create an audit table with the given name.
 *
 * Intentionally side-effect free: this does NOT run the migration. It just
 * returns a SQL string so callers can pipe it into their own migration
 * tooling (psql, drizzle, knex, custom runner, …).
 *
 * The result matches **running** `sql/001_init_audit_logs.sql` through
 * `sql/003_audit_logs_severity.sql` on the same table name: same columns
 * (including generated `outcome`, `error_code`, `severity`) and indexes.
 *
 * Validation:
 * - `tableName` is validated with the same policy as `tableName` in the
 *   base config: `/^[A-Za-z_][A-Za-z0-9_]*$/`, length 1..63.
 * - Throws `ConfigError` on invalid names.
 *
 * Note: PostgreSQL silently truncates identifiers longer than 63 chars.
 * When `tableName` is very long, the generated index names may be
 * truncated; keep table names short (<= 50 chars is safe) if this matters.
 */
export function generateInitSql(tableName: string): string {
  assertValidTableName(tableName, "generateInitSql");
  const t = tableName;
  return `-- Tracevault audit table: ${t}
--
-- Generated by \`generateInitSql("${t}")\`. Safe to run multiple times.
-- Includes generated columns and indexes from sql/002–003 (see README).

${auditTableDdlScript(t)}
`;
}
