import { assertValidTableName } from "./validator.js";

/**
 * Generate the DDL needed to create an audit table (matching Tracevault's
 * base schema) with the given name.
 *
 * Intentionally side-effect free: this does NOT run the migration. It just
 * returns a SQL string so callers can pipe it into their own migration
 * tooling (psql, drizzle, knex, custom runner, …).
 *
 * The schema matches the one shipped in `sql/001_init_audit_logs.sql`.
 * Calling `generateInitSql("audit_logs")` produces an equivalent DDL.
 *
 * Validation:
 * - `tableName` is validated with the same policy as `tableName` in the
 *   base config: `/^[A-Za-z_][A-Za-z0-9_]*$/`, length 1..63.
 * - Throws `ConfigError` on invalid names.
 *
 * Note: PostgreSQL silently truncates identifiers longer than 63 chars.
 * When `tableName` is very long, the generated index names may be
 * truncated; keep table names short (<= 50 chars is safe) if this matters.
 */
export function generateInitSql(tableName: string): string {
  assertValidTableName(tableName, "generateInitSql");
  const t = tableName;
  return `-- Tracevault audit table: ${t}
--
-- Generated by \`generateInitSql("${t}")\`. Safe to run multiple times.

CREATE TABLE IF NOT EXISTS "${t}" (
  id              UUID        PRIMARY KEY,
  event           VARCHAR     NOT NULL,
  actor_id        VARCHAR     NULL,
  actor_type      VARCHAR     NULL,
  target_id       VARCHAR     NULL,
  target_type     VARCHAR     NULL,
  data            JSONB       NULL,
  meta            JSONB       NULL,
  mode            VARCHAR     NOT NULL,
  occurred_at     TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  correlation_id  VARCHAR     NULL,
  request_id      VARCHAR     NULL,
  environment     VARCHAR     NULL
);

CREATE INDEX IF NOT EXISTS idx_${t}_event        ON "${t}" (event);
CREATE INDEX IF NOT EXISTS idx_${t}_actor        ON "${t}" (actor_id, actor_type);
CREATE INDEX IF NOT EXISTS idx_${t}_target       ON "${t}" (target_id, target_type);
CREATE INDEX IF NOT EXISTS idx_${t}_occurred_at  ON "${t}" (occurred_at DESC);
`;
}
